Default: &defaults
  database: shackage.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: shackage_test.sqlite3
  <<: *defaults

Staging:
  database: shackage_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: shackage_production.sqlite3
  poolsize: 100
  <<: *defaults
